name: bandung_tourism
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  shared_preferences: ^2.0.15
  dartz: ^0.10.0-nullsafety.2
  get_it: ^7.1.3
  google_fonts: ^3.0.1
  flutter_native_splash: ^2.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_native_splash:
  image: assets/splashscreen/logo_splash.png
  background_image: assets/splashscreen/bg_splash_screen.png
  background_image_dark: assets/splashscreen/bg_splash_screen_dark.png
  image_dark: assets/splashscreen/logo_splash_dark.png
  android_12:
    image: assets/splashscreen/logo_splash.png
    icon_background_color: "#F9FAFF"
    color: "#F9FAFF"

  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo/logo.png
    - assets/logo/logo_dark.png
    - assets/logo/gedung_sate.png
